language: node_js
node_js:
  "12"

sudo: false

os:
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated xctool || brew upgrade xctool; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome; fi  # Karma CI

before_script:
  - npm install

branches:
  only: master

notifications:
  email: true

script:
  - npm run test.all

cache:
  directories:
    - - "$HOME/.npm"
    - node_modules
